### ISSUE TITLE
A little typo on printFloat("intro40", intro32);

### ISSUE THREAD

**Issue by PPAC37** [ole00/pwmx_info#1]
Hello 

https://github.com/ole00/pwmx_info/blob/aa63dc1bca1f1c112dbb06a63b854438cd56f1c8/ole/pwmx/Pwmx.java#L59

A little typo on the output `printFloat("intro40", intro32);` ( (should be printFloat("intro40", intro**40**); ? )  but nothing really important as this field doesn't seem to be really usefull.)

And thank you for this project, which seems usable with ".dlp" files (for Anycubic Photon Ultra) generated with Photon Workshop V2.1.29RC14 (provided on the USB key), if i disable the version control throw (because: major version: 515 (0x203))
https://github.com/ole00/pwmx_info/blob/aa63dc1bca1f1c112dbb06a63b854438cd56f1c8/ole/pwmx/Reader.java#L71-L73

**Comment by ole00** [comment]
Thanks for the insight about the major version. I wonder whether it would be useful to have a set of those Photon Workshop files (.pwmx, .dlp etc) for future reference for developers that would want to support these printers - and can not normally access these files. BTW. I managed to add PWMX support to Prusa Slicer, maybe the .dlp files for Photon Ultra could be supported as well.  If you are curious see my other repo: https://github.com/ole00/PrusaSlicer

**Comment by PPAC37** [comment]
Yes, the Photon Ultra accepts and prints .pwmx files (major version 1). you just have to rename them to .dlp otherwise they are not visible.

If you want the test .dlp print files that came with the Photon Ultra, I made a copy of the key to my gdrive https://drive.google.com/drive/folders/1n9-Mopvfg08nocfT2fCG5jThwAumJjcM?usp=sharing


Otherwise, yes, I'm going to look at this integration of the pwmx format in SuperSlicer on your repository (even if my 'C' is a bit rusty, I'm intrigued) So thanks for the info.

**Comment by ole00** [comment]
Thanks for the files, I've downloaded them and will take a look at the .dlp examples.

**Comment by ole00** [comment]
I just checked SuperSlicer - as it is based on PrusaSlicer you might try to port the code I made for PrusaSlicer. Check these 2 commits:
https://github.com/ole00/PrusaSlicer/commit/7685e707434613e1a8ba50a189da61061e1a26d0
https://github.com/ole00/PrusaSlicer/commit/df0751716c2cc031cc8b3ffabd272ac55c1b0b6f
